---
apiVersion: v1
kind: Service
metadata:
  name: ocr
  labels:
    app: ocr
    run: ocr
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30082
  selector:
    app: ocr
---
apiVersion: extensions/v1beta
kind: Deployment
metadata:
  name: ocr-deployment
  namespace: default
  labels:
    app: ocr
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - image: oukajamehdi/flasknginxtesseract:latest
          imagePullPolicy: Always
          name: ocr
          ports:
            - containerPort: 80